image: ghcr.io/naastest/neon-billboard:7cb9d93af34f89535b2e7c32a6f1b1ab0ba4e2b3
namespace: payments-backend-dev
git_commit: "7cb9d93af34f89535b2e7c32a6f1b1ab0ba4e2b3"
env:
  APP_ENV: preview
  PR_NUMBER: "1"
  GIT_BRANCH: "feature/add-transaction-counter"
  GIT_COMMIT: "7cb9d93af34f89535b2e7c32a6f1b1ab0ba4e2b3"
ingress:
  enabled: true
  host: neon-billboard-pr-1.preview.naas.local
containerPort: 8080
replicaCount: 1
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: [ALL]
resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
probes:
  enabled: true
  path: /health
  readiness:
    initialDelaySeconds: 3
    periodSeconds: 10
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 30
    failureThreshold: 3
